#!/bin/sh
#
# Build ARM kernel for QEMU Raspberry Pi 1 Emulation
#
#######################################################
TOOLCHAIN=arm-none-eabi
COMMIT=rpi-4.20.y
export ARCH=arm
export CROSS_COMPILE=${TOOLCHAIN}-

if [ ! -f $COMMIT.tar.gz ]; then
	wget https://github.com/raspberrypi/linux/archive/$COMMIT.tar.gz -q --show-progress --continue
fi

# Extracting sources
if [ ! -d linux-$COMMIT ]; then
	tar xvf $COMMIT.tar.gz
	patch -Np1 -i ../linux-arm.patch -d linux-$COMMIT
fi

cd linux-$COMMIT

KERNEL_VERSION=$(make kernelversion)
KERNEL_TARGET_FILE_NAME=qemu-kernel-$KERNEL_VERSION
echo "Building Qemu Raspberry Pi kernel qemu-kernel-$KERNEL_VERSION"

# Config
make CC="ccache ${TOOLCHAIN}-gcc" versatile_defconfig
scripts/kconfig/merge_config.sh .config ../rpiconfig

# Compiling
make CC="ccache ${TOOLCHAIN}-gcc" xconfig
make -j 4 -k CC="ccache ${TOOLCHAIN}-gcc" bzImage dtbs
cat arch/arm/boot/zImage arch/arm/boot/dts/versatile-pb.dtb > ../build/$KERNEL_TARGET_FILE_NAME
