#!/bin/sh
#
# Build latest stable ARM kernel for QEMU Raspberry Pi 3 Emulation
#
#######################################################
TOOLCHAIN=aarch64-linux-gnu
COMMIT=$(wget --output-document - --quiet https://www.kernel.org/ | grep -A 1 "latest_link")
COMMIT=${COMMIT##*.tar.xz\">}
COMMIT=${COMMIT%</a>}
export ARCH=arm64
export CROSS_COMPILE=${TOOLCHAIN}-

if [ ! -f $COMMIT.tar.gz ]; then
	wget -q -c https://cdn.kernel.org/pub/linux/kernel/v4.x/linux-$COMMIT.tar.xz
fi

# Kernel Compilation
if [ ! -d linux-$COMMIT ]; then
	tar xvf linux-$COMMIT.tar.xz
fi

cd linux-$COMMIT

KERNEL_VERSION=$(make kernelversion)
KERNEL_TARGET_FILE_NAME=qemu-kernel-$KERNEL_VERSION-aarch64
echo "Building Qemu Raspberry Pi kernel qemu-kernel-$KERNEL_VERSION"

# Config
cp arch/arm/configs/vexpress_defconfig arch/arm64/configs
make -j 4 -k CC="ccache ${TOOLCHAIN}-gcc" vexpress_defconfig
scripts/kconfig/merge_config.sh .config ../rpiconfig

# Compiling
#make CC="ccache ${TOOLCHAIN}-gcc" ARCH=arm64 CROSS_COMPILE=${TOOLCHAIN}- xconfig
make -j 4 -k CC="ccache ${TOOLCHAIN}-gcc" Image.gz

cp arch/arm64/boot/Image.gz ../build/$KERNEL_TARGET_FILE_NAME
