#!/bin/sh
#
# Build latest stable ARM kernel for QEMU Raspberry Pi Emulation
#
#######################################################
TOOLCHAIN=arm-none-eabi
COMMIT=4.17.1

if [ ! -f $COMMIT.tar.gz ]; then
	wget https://cdn.kernel.org/pub/linux/kernel/v4.x/linux-$COMMIT.tar.xz -q --show-progress --continue
fi

# Kernel Compilation
if [ ! -d linux-$COMMIT ]; then
	tar xvf linux-$COMMIT.tar.xz
fi

cd linux-$COMMIT

KERNEL_VERSION=$(make kernelversion)
KERNEL_TARGET_FILE_NAME=qemu-kernel-$KERNEL_VERSION
MODULES_INSTALL_PATH=qemu-kernel-$KERNEL_VERSION-modules
echo "Building Qemu Raspberry Pi kernel qemu-kernel-$KERNEL_VERSION"

# Config
cp ../rpiconfig .config
# Compiling
#make CC="ccache ${TOOLCHAIN}-gcc" ARCH=arm CROSS_COMPILE=${TOOLCHAIN}- xconfig
make -j 4 -k CC="ccache ${TOOLCHAIN}-gcc" ARCH=arm CROSS_COMPILE=${TOOLCHAIN}- zImage

cp arch/arm/boot/zImage ../build/$KERNEL_TARGET_FILE_NAME

