#!/bin/sh
#
# Build latest stable ARM kernel for QEMU Raspberry Pi 2 Emulation
#
#######################################################
TOOLCHAIN=arm-none-eabi
COMMIT=$(curl -L -s https://www.kernel.org/ | grep -A 1 "latest_link")
COMMIT=${COMMIT##*.tar.xz\">}
COMMIT=${COMMIT%</a>}
export ARCH=arm
export CROSS_COMPILE=${TOOLCHAIN}-

curl -L -O -C - "https://cdn.kernel.org/pub/linux/kernel/v4.x/linux-$COMMIT.tar.xz"

# Kernel Compilation
if [ ! -d linux-$COMMIT ]; then
	tar xf linux-$COMMIT.tar.xz
fi

cd linux-$COMMIT

KERNEL_VERSION=$(make kernelversion)
KERNEL_TARGET_FILE_NAME=qemu-kernel-$KERNEL_VERSION
echo "Building Qemu Raspberry Pi kernel qemu-kernel-$KERNEL_VERSION"

# Config
make CC="ccache ${TOOLCHAIN}-gcc" ARCH=arm CROSS_COMPILE=${TOOLCHAIN}- vexpress_defconfig
scripts/kconfig/merge_config.sh .config ../rpiconfig

# Compiling
#make CC="ccache ${TOOLCHAIN}-gcc" ARCH=arm CROSS_COMPILE=${TOOLCHAIN}- xconfig
make -j 4 -k CC="ccache ${TOOLCHAIN}-gcc" ARCH=arm CROSS_COMPILE=${TOOLCHAIN}- zImage
#make -j 4 -k CC="ccache ${TOOLCHAIN}-gcc" ARCH=arm CROSS_COMPILE=${TOOLCHAIN}- dtbs

cp arch/arm/boot/zImage ../build/$KERNEL_TARGET_FILE_NAME

